ffmpeg:add missing header file
ffmpeg/libavdevice/nuttx.c:206:5: error: implicit declaration of function 'close'; did you mean 'pclose'? [-Werror=implicit-function-declaration]
  206 |     close(fd);
      |     ^~~~~
      |     pclose
At top level:
ffmpeg/libavfilter/af_amix.c:727:5: error: implicit declaration of function 'close'; did you mean 'pclose'? [-Werror=implicit-function-declaration]
  727 |     close(s->timer_fd);
      |     ^~~~~
      |     pclose
ffmpeg/libavfilter/af_amix.c: In function 'process_command':
ffmpeg/libavfilter/af_amix.c:806:13: error: implicit declaration of function 'read'; did you mean 'fread'? [-Werror=implicit-function-declaration]
  806 |             read(pollfd->fd, &exp, sizeof(exp));
      |             ^~~~
      |             fread
ffmpeg/libavfilter/sink_movie_async.c:82:5: error: unknown type name 'pthread_cond_t'
   82 |     pthread_cond_t            cond;
      |     ^~~~~~~~~~~~~~
ffmpeg/libavfilter/sink_movie_async.c: In function 'moviesink_send_cmd':
ffmpeg/libavfilter/sink_movie_async.c:116:5: error: implicit declaration of function 'pthread_mutex_lock' [-Werror=implicit-function-declaration]
  116 |     pthread_mutex_lock(&priv->mutex);
      |     ^~~~~~~~~~~~~~~~~~
ffmpeg/libavfilter/sink_movie_async.c:118:5: error: implicit declaration of function 'pthread_cond_signal' [-Werror=implicit-function-declaration]
  118 |     pthread_cond_signal(&priv->cond);
      |     ^~~~~~~~~~~~~~~~~~~
ffmpeg/libavfilter/sink_movie_async.c:119:5: error: implicit declaration of function 'pthread_mutex_unlock'; did you mean 'nxrmutex_unlock'? [-Werror=implicit-function-declaration]
  119 |     pthread_mutex_unlock(&priv->mutex);
      |     ^~~~~~~~~~~~~~~~~~~~
      |     nxrmutex_unlock
ffmpeg/libavfilter/sink_movie_async.c: In function 'moviesink_thread':
ffmpeg/libavfilter/sink_movie_async.c:669:13: error: implicit declaration of function 'pthread_cond_wait' [-Werror=implicit-function-declaration]
  669 |             pthread_cond_wait(&priv->cond, &priv->mutex);
      |             ^~~~~~~~~~~~~~~~~
ffmpeg/libavfilter/sink_movie_async.c: In function 'moviesink_uninit':
ffmpeg/libavfilter/sink_movie_async.c:763:5: error: implicit declaration of function 'pthread_mutex_destroy'; did you mean 'nxrmutex_destroy'? [-Werror=implicit-function-declaration]
  763 |     pthread_mutex_destroy(&priv->mutex);
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     nxrmutex_destroy
ffmpeg/libavfilter/sink_movie_async.c:764:5: error: implicit declaration of function 'pthread_cond_destroy' [-Werror=implicit-function-declaration]

Signed-off-by: anjiahao <anjiahao@xiaomi.com>